# theme = "nord"
chrome = "none"
# cursor = "bar"
# font-size = 16.0
# line-height = 1.3
padding = 12.0
# margin = 32.0
# title-emoji = "🚀"
font-family = "monospace"     # used with --no-font-embed
# theme-light = "github-light"       # set both or neither
# theme-dark = "github-dark"
# speed = 1.5
# idle-time-limit = 3.0
no-shadow = true
# no-embed-source = true

